name: app_environment
channels:
  - snowflake
dependencies:
  - geopandas=*
  - matplotlib=*
  - numpy=*
  - pandas=*
  - pydantic=*
  - pyproj=*
  - python-dotenv=*
  - rasterio=*
  - rioxarray=*
  - scikit-learn=*
  - seaborn=*
  - shapely=*
  - tqdm=*
  - xarray=*
